name: finalgoorm

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container_1
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: rocket
      POSTGRES_PASSWORD: qwer123!
    ports:
      - "5432:5432"
    networks:
      - app-tier
    volumes:
      - postgresvolume:/bitnami/postgresql  # bitnami 기준 디렉토리

  fastapi:
    build: ./nlp_service
    container_name: fastapi-server_f
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - KAKAO_API_KEY=${KAKAO_API_KEY}
    volumes:
      - ./nlp_service:/app
    working_dir: /app
    networks:
      - app-tier

volumes:
  postgresvolume:
